import { Club } from '@/types'

export const CLUBS: Club[] = [
  {
    slug: 'arsenal',
    name: 'Arsenal',
    subreddit: 'Gunners',
    primaryColor: '#EF0107',
    secondaryColor: '#023474',
    badgeEmoji: '🔴',
  },
  {
    slug: 'aston-villa',
    name: 'Aston Villa',
    subreddit: 'avfc',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
    badgeEmoji: '🟣',
  },
  {
    slug: 'brentford',
    name: 'Brentford',
    subreddit: 'Brentford',
    primaryColor: '#E30613',
    secondaryColor: '#FFD700',
    badgeEmoji: '🐝',
  },
  {
    slug: 'brighton',
    name: 'Brighton',
    subreddit: 'BrightonHoveAlbion',
    primaryColor: '#0057B8',
    secondaryColor: '#FFCD00',
    badgeEmoji: '🔵',
  },
  {
    slug: 'bournemouth',
    name: 'Bournemouth',
    subreddit: 'AFCBournemouth',
    primaryColor: '#DA291C',
    secondaryColor: '#000000',
    badgeEmoji: '🍒',
  },
  {
    slug: 'chelsea',
    name: 'Chelsea',
    subreddit: 'chelseafc',
    primaryColor: '#034694',
    secondaryColor: '#DBA111',
    badgeEmoji: '💙',
  },
  {
    slug: 'crystal-palace',
    name: 'Crystal Palace',
    subreddit: 'crystalpalace',
    primaryColor: '#1B458F',
    secondaryColor: '#C4122E',
    badgeEmoji: '🦅',
  },
  {
    slug: 'everton',
    name: 'Everton',
    subreddit: 'Everton',
    primaryColor: '#003399',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '💙',
  },
  {
    slug: 'fulham',
    name: 'Fulham',
    subreddit: 'fulhamfc',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '⚫',
  },
  {
    slug: 'ipswich',
    name: 'Ipswich',
    subreddit: 'ipswich',
    primaryColor: '#0044AA',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '🔵',
  },
  {
    slug: 'leicester',
    name: 'Leicester',
    subreddit: 'lcfc',
    primaryColor: '#003090',
    secondaryColor: '#FDBE11',
    badgeEmoji: '🦊',
  },
  {
    slug: 'liverpool',
    name: 'Liverpool',
    subreddit: 'LiverpoolFC',
    primaryColor: '#C8102E',
    secondaryColor: '#00B2A9',
    badgeEmoji: '🔴',
  },
  {
    slug: 'man-city',
    name: 'Man City',
    subreddit: 'MCFC',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
    badgeEmoji: '🩵',
  },
  {
    slug: 'man-united',
    name: 'Man United',
    subreddit: 'reddevils',
    primaryColor: '#DA291C',
    secondaryColor: '#FFE500',
    badgeEmoji: '👹',
  },
  {
    slug: 'newcastle',
    name: 'Newcastle',
    subreddit: 'NUFC',
    primaryColor: '#241F20',
    secondaryColor: '#41B6E6',
    badgeEmoji: '⬛',
  },
  {
    slug: 'nottingham-forest',
    name: "Nott'm Forest",
    subreddit: 'nffc',
    primaryColor: '#E53233',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '🌲',
  },
  {
    slug: 'southampton',
    name: 'Southampton',
    subreddit: 'SaintsFC',
    primaryColor: '#D71920',
    secondaryColor: '#130C0E',
    badgeEmoji: '⚽',
  },
  {
    slug: 'tottenham',
    name: 'Tottenham',
    subreddit: 'coys',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '🐓',
  },
  {
    slug: 'west-ham',
    name: 'West Ham',
    subreddit: 'Hammers',
    primaryColor: '#7A263A',
    secondaryColor: '#1BB1E7',
    badgeEmoji: '⚒️',
  },
  {
    slug: 'wolves',
    name: 'Wolves',
    subreddit: 'wolves',
    primaryColor: '#FDB913',
    secondaryColor: '#231F20',
    badgeEmoji: '🐺',
  },
]

export const CLUBS_BY_SLUG: Record<string, Club> = Object.fromEntries(
  CLUBS.map((c) => [c.slug, c])
)

export const CLUBS_BY_SUBREDDIT: Record<string, string> = Object.fromEntries(
  CLUBS.map((c) => [c.subreddit.toLowerCase(), c.slug])
)
