import { Club } from '@/types'

const PL_CDN = 'https://resources.premierleague.com/premierleague/badges'

export const CLUBS: Club[] = [
  {
    slug: 'arsenal',
    name: 'Arsenal',
    shortName: 'Arsenal',
    subreddit: 'Gunners',
    primaryColor: '#EF0107',
    secondaryColor: '#023474',
    badgeEmoji: '🔴',
    badgeUrl: `${PL_CDN}/t3.png`,
  },
  {
    slug: 'aston-villa',
    name: 'Aston Villa',
    shortName: 'Aston Villa',
    subreddit: 'avfc',
    primaryColor: '#670E36',
    secondaryColor: '#95BFE5',
    badgeEmoji: '🟣',
    badgeUrl: `${PL_CDN}/t7.png`,
  },
  {
    slug: 'brentford',
    name: 'Brentford',
    shortName: 'Brentford',
    subreddit: 'Brentford',
    primaryColor: '#E30613',
    secondaryColor: '#FFD700',
    badgeEmoji: '🐝',
    badgeUrl: `${PL_CDN}/t94.png`,
  },
  {
    slug: 'brighton',
    name: 'Brighton',
    shortName: 'Brighton',
    subreddit: 'BrightonHoveAlbion',
    primaryColor: '#0057B8',
    secondaryColor: '#FFCD00',
    badgeEmoji: '🔵',
    badgeUrl: `${PL_CDN}/t36.png`,
  },
  {
    slug: 'bournemouth',
    name: 'Bournemouth',
    shortName: 'Bournemouth',
    subreddit: 'AFCBournemouth',
    primaryColor: '#DA291C',
    secondaryColor: '#000000',
    badgeEmoji: '🍒',
    badgeUrl: `${PL_CDN}/t91.png`,
  },
  {
    slug: 'chelsea',
    name: 'Chelsea',
    shortName: 'Chelsea',
    subreddit: 'chelseafc',
    primaryColor: '#034694',
    secondaryColor: '#DBA111',
    badgeEmoji: '💙',
    badgeUrl: `${PL_CDN}/t8.png`,
  },
  {
    slug: 'crystal-palace',
    name: 'Crystal Palace',
    shortName: 'Palace',
    subreddit: 'crystalpalace',
    primaryColor: '#1B458F',
    secondaryColor: '#C4122E',
    badgeEmoji: '🦅',
    badgeUrl: `${PL_CDN}/t31.png`,
  },
  {
    slug: 'everton',
    name: 'Everton',
    shortName: 'Everton',
    subreddit: 'Everton',
    primaryColor: '#003399',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '💙',
    badgeUrl: `${PL_CDN}/t11.png`,
  },
  {
    slug: 'fulham',
    name: 'Fulham',
    shortName: 'Fulham',
    subreddit: 'fulhamfc',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '⚫',
    badgeUrl: `${PL_CDN}/t54.png`,
  },
  {
    slug: 'ipswich',
    name: 'Ipswich Town',
    shortName: 'Ipswich',
    subreddit: 'IpswichTown',
    primaryColor: '#0053A0',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '💙',
    badgeUrl: `${PL_CDN}/t40.png`,
  },
  {
    slug: 'leicester',
    name: 'Leicester City',
    shortName: 'Leicester',
    subreddit: 'lcfc',
    primaryColor: '#003DA5',
    secondaryColor: '#FDB913',
    badgeEmoji: '👑',
    badgeUrl: `${PL_CDN}/t13.png`,
  },
  {
    slug: 'liverpool',
    name: 'Liverpool',
    shortName: 'Liverpool',
    subreddit: 'LiverpoolFC',
    primaryColor: '#C8102E',
    secondaryColor: '#00B2A9',
    badgeEmoji: '🔴',
    badgeUrl: `${PL_CDN}/t14.png`,
  },
  {
    slug: 'man-city',
    name: 'Man City',
    shortName: 'Man City',
    subreddit: 'MCFC',
    primaryColor: '#6CABDD',
    secondaryColor: '#1C2C5B',
    badgeEmoji: '🩵',
    badgeUrl: `${PL_CDN}/t43.png`,
  },
  {
    slug: 'man-united',
    name: 'Man United',
    shortName: 'Man Utd',
    subreddit: 'reddevils',
    primaryColor: '#DA291C',
    secondaryColor: '#FFE500',
    badgeEmoji: '👹',
    badgeUrl: `${PL_CDN}/t1.png`,
  },
  {
    slug: 'newcastle',
    name: 'Newcastle',
    shortName: 'Newcastle',
    subreddit: 'NUFC',
    primaryColor: '#241F20',
    secondaryColor: '#41B6E6',
    badgeEmoji: '⬛',
    badgeUrl: `${PL_CDN}/t4.png`,
  },
  {
    slug: 'nottingham-forest',
    name: "Nott'm Forest",
    shortName: 'Forest',
    subreddit: 'nffc',
    primaryColor: '#E53233',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '🌲',
    badgeUrl: `${PL_CDN}/t17.png`,
  },
  {
    slug: 'southampton',
    name: 'Southampton',
    shortName: 'Southampton',
    subreddit: 'saintsfc',
    primaryColor: '#ED1A3B',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '⚪',
    badgeUrl: `${PL_CDN}/t20.png`,
  },
  {
    slug: 'tottenham',
    name: 'Tottenham',
    shortName: 'Spurs',
    subreddit: 'coys',
    primaryColor: '#132257',
    secondaryColor: '#FFFFFF',
    badgeEmoji: '🐓',
    badgeUrl: `${PL_CDN}/t6.png`,
  },
  {
    slug: 'west-ham',
    name: 'West Ham',
    shortName: 'West Ham',
    subreddit: 'Hammers',
    primaryColor: '#7A263A',
    secondaryColor: '#1BB1E7',
    badgeEmoji: '⚒️',
    badgeUrl: `${PL_CDN}/t21.png`,
  },
  {
    slug: 'wolves',
    name: 'Wolves',
    shortName: 'Wolves',
    subreddit: 'wolves',
    primaryColor: '#FDB913',
    secondaryColor: '#231F20',
    badgeEmoji: '🐺',
    badgeUrl: `${PL_CDN}/t39.png`,
  },
]

export const CLUBS_BY_SLUG: Record<string, Club> = Object.fromEntries(
  CLUBS.map((c) => [c.slug, c])
)

export const CLUBS_BY_SUBREDDIT: Record<string, string> = Object.fromEntries(
  CLUBS.map((c) => [c.subreddit.toLowerCase(), c.slug])
)
