-- API-Football Cache Tables
-- Run this migration to set up the caching infrastructure

-- Table 1: API-Football responses cache
CREATE TABLE IF NOT EXISTS api_cache (
  cache_key TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  cached_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  source TEXT NOT NULL DEFAULT 'api-football',
  CONSTRAINT cache_key_format CHECK (
    cache_key ~ '^[a-z_]+:[0-9]+:[0-9]+.*$'
  )
);

CREATE INDEX IF NOT EXISTS idx_api_cache_expires ON api_cache (expires_at);
CREATE INDEX IF NOT EXISTS idx_api_cache_source ON api_cache (source);

-- Table 2: Generated By The Numbers tiles (cached AI output)
CREATE TABLE IF NOT EXISTS by_the_numbers_tiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope TEXT NOT NULL CHECK (scope IN ('homepage', 'club')),
  club_slug TEXT,
  matchday INTEGER,
  tiles JSONB NOT NULL,
  accent_index INTEGER NOT NULL CHECK (accent_index >= 0 AND accent_index <= 3),
  editorial TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT club_required_for_club_scope CHECK (
    (scope = 'homepage' AND club_slug IS NULL) OR
    (scope = 'club' AND club_slug IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_btn_scope ON by_the_numbers_tiles (
  scope,
  club_slug,
  matchday
);
CREATE INDEX IF NOT EXISTS idx_btn_expires ON by_the_numbers_tiles (expires_at);

-- Comments for documentation
COMMENT ON TABLE api_cache IS 'Caching layer for API-Football responses. TTL managed by expires_at field.';
COMMENT ON COLUMN api_cache.cache_key IS 'Unique key: standings:39:2025, fixtures:39:2025:2026-03-02, etc.';
COMMENT ON COLUMN api_cache.source IS 'Data source identifier (e.g., api-football, anthropic-api)';

COMMENT ON TABLE by_the_numbers_tiles IS 'Cached AI-generated stat tiles from By The Numbers module.';
COMMENT ON COLUMN by_the_numbers_tiles.scope IS 'homepage or club (if club, requires club_slug)';
COMMENT ON COLUMN by_the_numbers_tiles.accent_index IS '0-based index of the highlighted tile (0-3)';
