import type { Metadata } from 'next'
import React from 'react'
import PageLayout from '@/components/PageLayout'

export const metadata: Metadata = {
  title: 'How PLHub Works — Sources, Index, AI Summaries',
  description:
    'How PLHub aggregates Premier League news, scores it by what matters, ' +
    'and surfaces it without the noise.',
}

export default function HowItWorksPage() {
  return (
    <PageLayout
      headline="How PLHub works"
      subheading="The sources, the scoring, the AI, and what we deliberately leave out."
    >
      <Section title="The Sources">
        <P>
          We aggregate from a curated list of editorial sources: BBC Sport,
          The Guardian, Sky Sports, talkSPORT, Goal.com, and more. No
          clickbait sites. No accounts that exist to manufacture outrage.
          If it&apos;s not worth your time, it&apos;s not in the feed.
        </P>
      </Section>

      <Section title="The PLHub Index">
        <P>
          Every story gets a score. Not based on clicks or social shares
          — those just reward whoever shouts loudest. The PLHub Index
          scores each story across four things:
        </P>
        <IndexFactors />
        <P>
          The top score wins the top slot. A match report from a
          correspondent who was actually there scores higher than a
          tabloid rumour with a question mark in the headline. That&apos;s
          the idea.
        </P>
      </Section>

      <Section title="The AI Summaries">
        <P>
          Each story gets a three-sentence summary generated by AI.
          Not a synopsis, not a spoiler — a proper summary written in
          plain English, in a voice designed by the person who built
          this site, following editorial rules he set.
        </P>
        <P>
          Sentence one: what happened. Sentence two: why it matters.
          Sentence three: the thing your mate would say about it at the pub.
        </P>
        <P>
          The AI writes the words. The judgement about what matters,
          what the voice sounds like, and what we will and won&apos;t say
          — that&apos;s human. The original article is always one tap away.
        </P>
      </Section>

      <Section title="The Snapshot">
        <P>
          Once a day — updated around matchdays — The Snapshot
          assembles the whole picture in one place. Top stories, the
          table, upcoming fixtures, transfers, the stat worth knowing.
          A full PL briefing in under two minutes. Your morning coffee,
          sorted.
        </P>
      </Section>

      <Section title="What We Don't Do">
        <DoNots />
      </Section>

      <BackLink />
    </PageLayout>
  )
}

// ── Local components ──────────────────────────────────────────────────

function Section({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        paddingBottom: '24px',
        borderBottom: '1px solid var(--plh-border)',
      }}
    >
      <h2
        style={{
          fontSize: '20px',
          fontWeight: 700,
          color: 'var(--plh-teal)',
          margin: 0,
          fontFamily: "'Sora', sans-serif",
        }}
      >
        {title}
      </h2>
      {children}
    </div>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: '17px',
        lineHeight: 1.75,
        margin: 0,
        color: '#FFFFFF',
        fontWeight: 300,
        fontFamily: "'Sora', sans-serif",
      }}
    >
      {children}
    </p>
  )
}

function IndexFactors() {
  const factors = [
    { label: 'Credibility', desc: "Who's reporting it and how reliable they are" },
    { label: 'Recency', desc: 'How fresh the story is' },
    { label: 'Significance', desc: 'Does it actually matter to the PL picture' },
    { label: 'Corroboration', desc: 'Is anyone else reporting the same thing' },
  ]
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
      {factors.map((f) => (
        <div
          key={f.label}
          style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}
        >
          <span
            style={{
              color: 'var(--plh-pink)',
              fontWeight: 700,
              fontSize: '16px',
              flexShrink: 0,
              paddingTop: '2px',
            }}
          >
            —
          </span>
          <span
            style={{
              fontSize: '16px',
              color: '#FFFFFF',
              fontFamily: "'Sora', sans-serif",
              lineHeight: 1.6,
            }}
          >
            <strong style={{ color: 'var(--plh-text-100)', fontWeight: 600 }}>
              {f.label}
            </strong>
            {` — ${f.desc}`}
          </span>
        </div>
      ))}
    </div>
  )
}

function DoNots() {
  const items = [
    'No gambling ads. Ever. Not even adjacent ones.',
    "No paywalls. The feed is free. It's staying free.",
    'No popups. No cookie consent walls that take forty seconds to dismiss.',
    'No reaction content. No one screaming at a camera.',
    "No manufactured outrage. No making a living out of your misery.",
    'No opinion columns dressed up as news.',
  ]
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
      {items.map((item, i) => (
        <div
          key={i}
          style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}
        >
          <span
            style={{
              color: 'var(--plh-teal)',
              fontWeight: 700,
              fontSize: '16px',
              flexShrink: 0,
            }}
          >
            ✓
          </span>
          <span
            style={{
              fontSize: '16px',
              color: '#FFFFFF',
              fontFamily: "'Sora', sans-serif",
              lineHeight: 1.6,
            }}
          >
            {item}
          </span>
        </div>
      ))}
    </div>
  )
}

function BackLink() {
  return (
    <a
      href="/"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '14px',
        color: 'var(--plh-teal)',
        textDecoration: 'none',
        fontFamily: "'Sora', sans-serif",
        marginTop: '8px',
      }}
    >
      ← Back to PLHub
    </a>
  )
}
