export type Club = {
  slug: string;
  name: string;
  shortName: string;
  code: string;
  primaryColour: string;
  secondaryColour: string;
  competitions: string[];
  founded: number;
  stadium: string;
  city: string;
  manager: string;
  footballDataId: number;
  apiSportsId: number;
};

export const CLUBS: Record<string, Club> = {
  arsenal: {
    slug: 'arsenal',
    name: 'Arsenal Football Club',
    shortName: 'Arsenal',
    code: 'ARS',
    primaryColour: '#EF0107',
    secondaryColour: '#063672',
    competitions: ['PL', 'UCL'],
    founded: 1886,
    stadium: 'Emirates Stadium',
    city: 'London',
    manager: 'Mikel Arteta',
    footballDataId: 57,
    apiSportsId: 42,
  },
  'aston-villa': {
    slug: 'aston-villa',
    name: 'Aston Villa Football Club',
    shortName: 'Aston Villa',
    code: 'AVL',
    primaryColour: '#670E36',
    secondaryColour: '#95BFE5',
    competitions: ['PL', 'UCL'],
    founded: 1874,
    stadium: 'Villa Park',
    city: 'Birmingham',
    manager: 'Unai Emery',
    footballDataId: 58,
    apiSportsId: 66,
  },
  bournemouth: {
    slug: 'bournemouth',
    name: 'AFC Bournemouth',
    shortName: 'Bournemouth',
    code: 'BOU',
    primaryColour: '#DA291C',
    secondaryColour: '#000000',
    competitions: ['PL'],
    founded: 1899,
    stadium: 'Vitality Stadium',
    city: 'Bournemouth',
    manager: 'Andoni Iraola',
    footballDataId: 1044,
    apiSportsId: 35,
  },
  brentford: {
    slug: 'brentford',
    name: 'Brentford Football Club',
    shortName: 'Brentford',
    code: 'BRE',
    primaryColour: '#FFD700',
    secondaryColour: '#E30613',
    competitions: ['PL'],
    founded: 1889,
    stadium: 'Gtech Community Stadium',
    city: 'London',
    manager: 'Thomas Frank',
    footballDataId: 402,
    apiSportsId: 55,
  },
  brighton: {
    slug: 'brighton',
    name: 'Brighton & Hove Albion Football Club',
    shortName: 'Brighton',
    code: 'BHA',
    primaryColour: '#0057B8',
    secondaryColour: '#FFFFFF',
    competitions: ['PL'],
    founded: 1901,
    stadium: 'Amex Stadium',
    city: 'Brighton',
    manager: 'Fabian Hürzeler',
    footballDataId: 397,
    apiSportsId: 51,
  },
  chelsea: {
    slug: 'chelsea',
    name: 'Chelsea Football Club',
    shortName: 'Chelsea',
    code: 'CHE',
    primaryColour: '#034694',
    secondaryColour: '#DBA111',
    competitions: ['PL', 'UCL'],
    founded: 1905,
    stadium: 'Stamford Bridge',
    city: 'London',
    manager: 'Enzo Maresca',
    footballDataId: 61,
    apiSportsId: 49,
  },
  'crystal-palace': {
    slug: 'crystal-palace',
    name: 'Crystal Palace Football Club',
    shortName: 'Crystal Palace',
    code: 'CRY',
    primaryColour: '#1B458F',
    secondaryColour: '#C4122E',
    competitions: ['PL'],
    founded: 1905,
    stadium: 'Selhurst Park',
    city: 'London',
    manager: 'Oliver Glasner',
    footballDataId: 354,
    apiSportsId: 52,
  },
  everton: {
    slug: 'everton',
    name: 'Everton Football Club',
    shortName: 'Everton',
    code: 'EVE',
    primaryColour: '#003399',
    secondaryColour: '#FFFFFF',
    competitions: ['PL'],
    founded: 1878,
    stadium: 'Goodison Park',
    city: 'Liverpool',
    manager: 'Sean Dyche',
    footballDataId: 62,
    apiSportsId: 45,
  },
  fulham: {
    slug: 'fulham',
    name: 'Fulham Football Club',
    shortName: 'Fulham',
    code: 'FUL',
    primaryColour: '#CC0000',
    secondaryColour: '#000000',
    competitions: ['PL'],
    founded: 1879,
    stadium: 'Craven Cottage',
    city: 'London',
    manager: 'Marco Silva',
    footballDataId: 63,
    apiSportsId: 36,
  },
  ipswich: {
    slug: 'ipswich',
    name: 'Ipswich Town Football Club',
    shortName: 'Ipswich',
    code: 'IPS',
    primaryColour: '#0044A9',
    secondaryColour: '#FFFFFF',
    competitions: ['PL'],
    founded: 1878,
    stadium: 'Portman Road',
    city: 'Ipswich',
    manager: 'Kieran McKenna',
    footballDataId: 57,
    apiSportsId: 57,
  },
  leicester: {
    slug: 'leicester',
    name: 'Leicester City Football Club',
    shortName: 'Leicester',
    code: 'LEI',
    primaryColour: '#003090',
    secondaryColour: '#FDBE11',
    competitions: ['PL'],
    founded: 1884,
    stadium: 'King Power Stadium',
    city: 'Leicester',
    manager: 'Ruud van Nistelrooy',
    footballDataId: 338,
    apiSportsId: 46,
  },
  liverpool: {
    slug: 'liverpool',
    name: 'Liverpool Football Club',
    shortName: 'Liverpool',
    code: 'LIV',
    primaryColour: '#C8102E',
    secondaryColour: '#F6EB61',
    competitions: ['PL', 'UCL'],
    founded: 1892,
    stadium: 'Anfield',
    city: 'Liverpool',
    manager: 'Arne Slot',
    footballDataId: 64,
    apiSportsId: 40,
  },
  'man-city': {
    slug: 'man-city',
    name: 'Manchester City Football Club',
    shortName: 'Man City',
    code: 'MCI',
    primaryColour: '#6CABDD',
    secondaryColour: '#1C2C5B',
    competitions: ['PL', 'UCL'],
    founded: 1880,
    stadium: 'Etihad Stadium',
    city: 'Manchester',
    manager: 'Pep Guardiola',
    footballDataId: 65,
    apiSportsId: 50,
  },
  'man-utd': {
    slug: 'man-utd',
    name: 'Manchester United Football Club',
    shortName: 'Man Utd',
    code: 'MUN',
    primaryColour: '#DA291C',
    secondaryColour: '#FBE122',
    competitions: ['PL', 'EL'],
    founded: 1878,
    stadium: 'Old Trafford',
    city: 'Manchester',
    manager: 'Ruben Amorim',
    footballDataId: 66,
    apiSportsId: 33,
  },
  newcastle: {
    slug: 'newcastle',
    name: 'Newcastle United Football Club',
    shortName: 'Newcastle',
    code: 'NEW',
    primaryColour: '#241F20',
    secondaryColour: '#FFFFFF',
    competitions: ['PL'],
    founded: 1892,
    stadium: 'St. James\' Park',
    city: 'Newcastle',
    manager: 'Eddie Howe',
    footballDataId: 67,
    apiSportsId: 34,
  },
  'nottm-forest': {
    slug: 'nottm-forest',
    name: 'Nottingham Forest Football Club',
    shortName: 'Nottm Forest',
    code: 'NFO',
    primaryColour: '#DD0000',
    secondaryColour: '#FFFFFF',
    competitions: ['PL', 'EL'],
    founded: 1865,
    stadium: 'The City Ground',
    city: 'Nottingham',
    manager: 'Nuno Espírito Santo',
    footballDataId: 351,
    apiSportsId: 65,
  },
  southampton: {
    slug: 'southampton',
    name: 'Southampton Football Club',
    shortName: 'Southampton',
    code: 'SOU',
    primaryColour: '#D71920',
    secondaryColour: '#130C0E',
    competitions: ['PL'],
    founded: 1885,
    stadium: 'St. Mary\'s Stadium',
    city: 'Southampton',
    manager: 'Ivan Juric',
    footballDataId: 340,
    apiSportsId: 41,
  },
  spurs: {
    slug: 'spurs',
    name: 'Tottenham Hotspur Football Club',
    shortName: 'Spurs',
    code: 'TOT',
    primaryColour: '#132257',
    secondaryColour: '#FFFFFF',
    competitions: ['PL', 'EL'],
    founded: 1882,
    stadium: 'Tottenham Hotspur Stadium',
    city: 'London',
    manager: 'Ange Postecoglou',
    footballDataId: 73,
    apiSportsId: 47,
  },
  'west-ham': {
    slug: 'west-ham',
    name: 'West Ham United Football Club',
    shortName: 'West Ham',
    code: 'WHU',
    primaryColour: '#7A263A',
    secondaryColour: '#1BB1E7',
    competitions: ['PL'],
    founded: 1895,
    stadium: 'London Stadium',
    city: 'London',
    manager: 'Julen Lopetegui',
    footballDataId: 563,
    apiSportsId: 48,
  },
  wolves: {
    slug: 'wolves',
    name: 'Wolverhampton Wanderers Football Club',
    shortName: 'Wolves',
    code: 'WOL',
    primaryColour: '#FDB913',
    secondaryColour: '#231F20',
    competitions: ['PL'],
    founded: 1877,
    stadium: 'Molineux Stadium',
    city: 'Wolverhampton',
    manager: 'Vitor Pereira',
    footballDataId: 76,
    apiSportsId: 39,
  },
};

export function getClub(slug: string): Club | undefined {
  return CLUBS[slug];
}

export function getAllClubSlugs(): string[] {
  return Object.keys(CLUBS);
}

export function getClubsByCompetition(competitionId: string): Club[] {
  return Object.values(CLUBS).filter(c => c.competitions.includes(competitionId));
}
